### ISSUE TITLE
SSL - No data due to SSL error

### ISSUE THREAD

**Issue by LoveMyData** [planningalerts-scrapers/darebin#1]
SSL error with OpenSSL

/app/vendor/bundle/ruby/1.9.1/gems/net-http-persistent-2.5.2/lib/net/http/persistent/ssl_reuse.rb:70:in `connect' : SSL_connect SYSCALL returned=5 errno=0 state=unknown state (OpenSSL::SSL::SSLError)

Maybe related to https://github.com/openaustralia/morph/issues/939

**Comment by JasonThomasData** [comment]
The issue with this scraper seems to be the server wants a particular kind of handshake.

I tried catching the error in my ruby script, but no change in error message.

This [online tool](https://cryptoreport.websecurity.symantec.com/checker/views/certCheck.jsp) showed it was not accepting TLS 1.2.

I tried setting the SSL definition in `Mechanize`, like this:

```
agent = Mechanize.new {|a| a.ssl_version, a.verify_mode = 'TLSv1_1'}
```

I did this for all the SSL definitions on [this page](https://docs.python.org/2/library/ssl.html) (it's a Python page but `Mechanize` was accepting these definitions).

I also tried gems `net/http` and `httparty` in place of `Mechanize` with no success.

**Comment by henare** [comment]
[This was the solution](https://stackoverflow.com/questions/33572956/ruby-ssl-connect-syscall-returned-5-errno-0-state-unknown-state-opensslssl) but I had to get it to work with Mechanize. That meant digging into the bowels of a number of libraries. It's fixed in a really hacky way that I probably wouldn't use on anything but a scraper.
